Fixing more C# 7.3 compiler errors
error CS0136: A local or parameter named 'totalVoxels' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter